steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run with secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-backend' # Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # Change to your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'MONGO_URI=MONGO_URI:latest,MONGO_DB_NAME=MONGO_DB_NAME:latest,PASSWORD_SALT=PASSWORD_SALT:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest'
      # Format: ENV_VAR=SECRET_NAME:VERSION

images:
  - 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
