@host = http://localhost:8080
@access_token = 
@refresh_token = 
@test_email = imrishabh95@gmail.com

###
# @name Code
# Creates a new user account with a secure JSON body.
POST {{host}}/send-verification-code
Content-Type: application/json

{
    "email": "{{test_email}}"
}

###
# @name Signup
# Creates a new user account with a secure JSON body.
POST {{host}}/create-user
Content-Type: application/json

{
    "email": "{{test_email}}",
    "code": "103711",
    "password": "cleanup",
    "first_name": "Cleanup",
    "last_name": "User"
}

###
# @name Login
# Logs in and automatically captures tokens.
POST {{host}}/login
Content-Type: application/json

{
    "email": "{{test_email}}",
    "password": "cleanup"
}

###
# @name VerifyLogin
# Uses the captured token to access a protected endpoint.
GET {{host}}/users/me
Authorization: Bearer {{Login.response.body.access_token}}

###
# @name Cleanup
# Deletes the user account created during the signup step.
# Requires the access token to authenticate.
DELETE {{host}}/users/{{test_email}}
Authorization: Bearer {{Login.response.body.access_token}}